"""initial schema

Revision ID: 7936901a1881
Revises: 
Create Date: 2025-10-07 10:00:34.839816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7936901a1881'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centros_custo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('orcamento_anual', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('responsavel_financeiro', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_centros_custo_codigo'), 'centros_custo', ['codigo'], unique=True)
    op.create_index(op.f('ix_centros_custo_id'), 'centros_custo', ['id'], unique=False)
    op.create_index(op.f('ix_centros_custo_nome'), 'centros_custo', ['nome'], unique=False)
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('contato_nome', sa.String(length=100), nullable=True),
    sa.Column('contato_email', sa.String(length=150), nullable=True),
    sa.Column('contato_telefone', sa.String(length=20), nullable=True),
    sa.Column('contato_celular', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('site', sa.String(length=200), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fornecedores_cnpj'), 'fornecedores', ['cnpj'], unique=True)
    op.create_index(op.f('ix_fornecedores_cpf'), 'fornecedores', ['cpf'], unique=True)
    op.create_index(op.f('ix_fornecedores_id'), 'fornecedores', ['id'], unique=False)
    op.create_index(op.f('ix_fornecedores_nome'), 'fornecedores', ['nome'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_code'), 'locations', ['code'], unique=True)
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'USER', 'AUDITOR', 'TECHNICIAN', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='userstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('employee_id', sa.String(length=50), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('condition', sa.JSON(), nullable=False),
    sa.Column('alert_template', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('asset_types', sa.JSON(), nullable=True),
    sa.Column('locations', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('evaluation_interval', sa.Integer(), nullable=True),
    sa.Column('cooldown_period', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_id'), 'alert_rules', ['id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_tag', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_tag'), 'assets', ['asset_tag'], unique=True)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_location_id'), 'assets', ['location_id'], unique=False)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.create_table('auditorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('escopo', sa.JSON(), nullable=True),
    sa.Column('criterios_priorizacao', sa.JSON(), nullable=True),
    sa.Column('escopo_setores', sa.String(length=500), nullable=True),
    sa.Column('escopo_locais', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_inicio_planejada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_fim_planejada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_fim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_fim_prevista', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_fim_real', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_reconciliacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_finalizacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=False),
    sa.Column('responsavel_auditoria', sa.Integer(), nullable=True),
    sa.Column('equipe_auditores', sa.JSON(), nullable=True),
    sa.Column('finalizado_por', sa.Integer(), nullable=True),
    sa.Column('total_itens_esperados', sa.Integer(), nullable=True),
    sa.Column('total_itens_verificados', sa.Integer(), nullable=True),
    sa.Column('total_conformes', sa.Integer(), nullable=True),
    sa.Column('total_divergentes', sa.Integer(), nullable=True),
    sa.Column('total_nao_encontrados', sa.Integer(), nullable=True),
    sa.Column('total_extras', sa.Integer(), nullable=True),
    sa.Column('total_itens', sa.Integer(), nullable=True),
    sa.Column('itens_conformes', sa.Integer(), nullable=True),
    sa.Column('itens_divergentes', sa.Integer(), nullable=True),
    sa.Column('itens_nao_encontrados', sa.Integer(), nullable=True),
    sa.Column('itens_extras', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('observacoes_finais', sa.Text(), nullable=True),
    sa.Column('hash_auditoria', sa.String(length=64), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['finalizado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['responsavel_auditoria'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditorias_codigo'), 'auditorias', ['codigo'], unique=True)
    op.create_index(op.f('ix_auditorias_id'), 'auditorias', ['id'], unique=False)
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=100), nullable=False),
    sa.Column('machine_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('machine_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('operating_system', sa.String(length=20), nullable=True),
    sa.Column('os_version', sa.String(length=100), nullable=True),
    sa.Column('architecture', sa.String(length=20), nullable=True),
    sa.Column('cpu_model', sa.String(length=200), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('ram_total_gb', sa.Float(), nullable=True),
    sa.Column('disk_total_gb', sa.Float(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('agent_version', sa.String(length=50), nullable=True),
    sa.Column('agent_last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_config', sa.JSON(), nullable=True),
    sa.Column('last_boot_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), nullable=True),
    sa.Column('cpu_usage_percent', sa.Float(), nullable=True),
    sa.Column('ram_usage_percent', sa.Float(), nullable=True),
    sa.Column('disk_usage_percent', sa.Float(), nullable=True),
    sa.Column('antivirus_status', sa.String(length=50), nullable=True),
    sa.Column('firewall_status', sa.String(length=50), nullable=True),
    sa.Column('last_security_scan', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_compliant', sa.Boolean(), nullable=True),
    sa.Column('compliance_notes', sa.Text(), nullable=True),
    sa.Column('last_compliance_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_managed', sa.Boolean(), nullable=True),
    sa.Column('management_notes', sa.Text(), nullable=True),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_assigned_user_id'), 'machines', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_machines_hostname'), 'machines', ['hostname'], unique=True)
    op.create_index(op.f('ix_machines_id'), 'machines', ['id'], unique=False)
    op.create_index(op.f('ix_machines_ip_address'), 'machines', ['ip_address'], unique=False)
    op.create_index(op.f('ix_machines_location_id'), 'machines', ['location_id'], unique=False)
    op.create_index(op.f('ix_machines_mac_address'), 'machines', ['mac_address'], unique=False)
    op.create_index(op.f('ix_machines_machine_id'), 'machines', ['machine_id'], unique=True)
    op.create_index(op.f('ix_machines_machine_type'), 'machines', ['machine_type'], unique=False)
    op.create_index(op.f('ix_machines_operating_system'), 'machines', ['operating_system'], unique=False)
    op.create_index(op.f('ix_machines_status'), 'machines', ['status'], unique=False)
    op.create_table('setores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('gestor_id', sa.Integer(), nullable=True),
    sa.Column('centro_custo_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['centro_custo_id'], ['centros_custo.id'], ),
    sa.ForeignKeyConstraint(['gestor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setores_codigo'), 'setores', ['codigo'], unique=True)
    op.create_index(op.f('ix_setores_id'), 'setores', ['id'], unique=False)
    op.create_index(op.f('ix_setores_nome'), 'setores', ['nome'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('alert_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('machine_hostname', sa.String(length=100), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledgment_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated_to', sa.Integer(), nullable=True),
    sa.Column('notification_count', sa.Integer(), nullable=True),
    sa.Column('last_notification_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notification_channels', sa.JSON(), nullable=True),
    sa.Column('auto_resolve', sa.Boolean(), nullable=True),
    sa.Column('auto_resolve_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('parent_alert_id', sa.Integer(), nullable=True),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['escalated_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['parent_alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_number'), 'alerts', ['alert_number'], unique=True)
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_asset_id'), 'alerts', ['asset_id'], unique=False)
    op.create_index(op.f('ix_alerts_category'), 'alerts', ['category'], unique=False)
    op.create_index(op.f('ix_alerts_correlation_id'), 'alerts', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_location_id'), 'alerts', ['location_id'], unique=False)
    op.create_index(op.f('ix_alerts_machine_hostname'), 'alerts', ['machine_hostname'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_source'), 'alerts', ['source'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_table('asset_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('record_hash', sa.String(length=64), nullable=True),
    sa.Column('signature', sa.String(length=128), nullable=True),
    sa.Column('signature_algorithm', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_audits_action'), 'asset_audits', ['action'], unique=False)
    op.create_index(op.f('ix_asset_audits_asset_id'), 'asset_audits', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_audits_id'), 'asset_audits', ['id'], unique=False)
    op.create_table('locais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('empresa', sa.String(length=100), nullable=False),
    sa.Column('unidade', sa.String(length=100), nullable=False),
    sa.Column('andar', sa.String(length=20), nullable=True),
    sa.Column('sala', sa.String(length=50), nullable=True),
    sa.Column('posicao', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('capacidade_ativos', sa.Integer(), nullable=True),
    sa.Column('setor_id', sa.Integer(), nullable=True),
    sa.Column('responsavel_local', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locais_codigo'), 'locais', ['codigo'], unique=True)
    op.create_index(op.f('ix_locais_id'), 'locais', ['id'], unique=False)
    op.create_table('machine_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('metric_unit', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_metrics_category'), 'machine_metrics', ['category'], unique=False)
    op.create_index(op.f('ix_machine_metrics_id'), 'machine_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_machine_metrics_machine_id'), 'machine_metrics', ['machine_id'], unique=False)
    op.create_index(op.f('ix_machine_metrics_metric_name'), 'machine_metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_machine_metrics_recorded_at'), 'machine_metrics', ['recorded_at'], unique=False)
    op.create_table('movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movement_number', sa.String(length=50), nullable=False),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('from_location_id', sa.Integer(), nullable=True),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('to_location_id', sa.Integer(), nullable=True),
    sa.Column('to_user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_return_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('carrier', sa.String(length=100), nullable=True),
    sa.Column('condition_before', sa.String(length=50), nullable=True),
    sa.Column('condition_after', sa.String(length=50), nullable=True),
    sa.Column('condition_notes', sa.Text(), nullable=True),
    sa.Column('cost', sa.String(length=20), nullable=True),
    sa.Column('cost_center', sa.String(length=100), nullable=True),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movements_asset_id'), 'movements', ['asset_id'], unique=False)
    op.create_index(op.f('ix_movements_from_location_id'), 'movements', ['from_location_id'], unique=False)
    op.create_index(op.f('ix_movements_from_user_id'), 'movements', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_movements_id'), 'movements', ['id'], unique=False)
    op.create_index(op.f('ix_movements_movement_number'), 'movements', ['movement_number'], unique=True)
    op.create_index(op.f('ix_movements_movement_type'), 'movements', ['movement_type'], unique=False)
    op.create_index(op.f('ix_movements_status'), 'movements', ['status'], unique=False)
    op.create_index(op.f('ix_movements_to_location_id'), 'movements', ['to_location_id'], unique=False)
    op.create_index(op.f('ix_movements_to_user_id'), 'movements', ['to_user_id'], unique=False)
    op.create_table('responsaveis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('matricula', sa.String(length=50), nullable=True),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.Column('gestor_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gestor_id'], ['responsaveis.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_responsaveis_email'), 'responsaveis', ['email'], unique=True)
    op.create_index(op.f('ix_responsaveis_id'), 'responsaveis', ['id'], unique=False)
    op.create_index(op.f('ix_responsaveis_matricula'), 'responsaveis', ['matricula'], unique=True)
    op.create_index(op.f('ix_responsaveis_nome'), 'responsaveis', ['nome'], unique=False)
    op.create_table('software_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('install_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('install_location', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_licensed', sa.Boolean(), nullable=True),
    sa.Column('license_key', sa.String(length=200), nullable=True),
    sa.Column('is_vulnerable', sa.Boolean(), nullable=True),
    sa.Column('vulnerability_count', sa.Integer(), nullable=True),
    sa.Column('last_vulnerability_scan', sa.DateTime(timezone=True), nullable=True),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_software_inventory_id'), 'software_inventory', ['id'], unique=False)
    op.create_index(op.f('ix_software_inventory_machine_id'), 'software_inventory', ['machine_id'], unique=False)
    op.create_index(op.f('ix_software_inventory_name'), 'software_inventory', ['name'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('machine_hostname', sa.String(length=100), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('requester_name', sa.String(length=100), nullable=True),
    sa.Column('requester_email', sa.String(length=100), nullable=True),
    sa.Column('requester_phone', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('actual_hours', sa.Float(), nullable=True),
    sa.Column('sla_due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_breached', sa.Boolean(), nullable=True),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_asset_id'), 'tickets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_tickets_assigned_to'), 'tickets', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_tickets_category'), 'tickets', ['category'], unique=False)
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_location_id'), 'tickets', ['location_id'], unique=False)
    op.create_index(op.f('ix_tickets_machine_hostname'), 'tickets', ['machine_hostname'], unique=False)
    op.create_index(op.f('ix_tickets_priority'), 'tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_ticket_number'), 'tickets', ['ticket_number'], unique=True)
    op.create_table('ativos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('patrimonio', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('subcategoria', sa.String(length=100), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('ns_serie', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('valor_aquisicao', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('data_compra', sa.DateTime(), nullable=True),
    sa.Column('nota_fiscal', sa.String(length=100), nullable=True),
    sa.Column('vida_util_meses', sa.Integer(), nullable=True),
    sa.Column('deprec_linear', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('centro_custo_id', sa.Integer(), nullable=True),
    sa.Column('setor_id', sa.Integer(), nullable=True),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('garantia_ate', sa.DateTime(), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('fotos', sa.JSON(), nullable=True),
    sa.Column('qr_code', sa.String(length=200), nullable=True),
    sa.Column('nfc_tag', sa.String(length=100), nullable=True),
    sa.Column('etiqueta_impressa', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['centro_custo_id'], ['centros_custo.id'], ),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['locais.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['responsaveis.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nfc_tag'),
    sa.UniqueConstraint('qr_code')
    )
    op.create_index(op.f('ix_ativos_codigo'), 'ativos', ['codigo'], unique=True)
    op.create_index(op.f('ix_ativos_id'), 'ativos', ['id'], unique=False)
    op.create_index(op.f('ix_ativos_ns_serie'), 'ativos', ['ns_serie'], unique=True)
    op.create_index(op.f('ix_ativos_patrimonio'), 'ativos', ['patrimonio'], unique=True)
    op.create_table('ticket_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_comments_id'), 'ticket_comments', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_comments_ticket_id'), 'ticket_comments', ['ticket_id'], unique=False)
    op.create_table('auditoria_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auditoria_id', sa.Integer(), nullable=False),
    sa.Column('ativo_id', sa.Integer(), nullable=True),
    sa.Column('leitura_codigo', sa.String(length=100), nullable=True),
    sa.Column('leitura_manual', sa.String(length=100), nullable=True),
    sa.Column('codigo_lido', sa.String(length=100), nullable=True),
    sa.Column('resultado', sa.String(length=30), nullable=False),
    sa.Column('divergencias', sa.Text(), nullable=True),
    sa.Column('local_esperado_id', sa.Integer(), nullable=True),
    sa.Column('local_encontrado_id', sa.Integer(), nullable=True),
    sa.Column('responsavel_esperado_id', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('evidencias', sa.JSON(), nullable=True),
    sa.Column('estado_encontrado', sa.String(length=30), nullable=True),
    sa.Column('observacoes_esperadas', sa.Text(), nullable=True),
    sa.Column('observacoes_coleta', sa.Text(), nullable=True),
    sa.Column('foto_evidencia_url', sa.String(length=500), nullable=True),
    sa.Column('data_coleta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verificado_por', sa.Integer(), nullable=False),
    sa.Column('timestamp_verificacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('coordenadas_gps', sa.String(length=50), nullable=True),
    sa.Column('coletado_por', sa.Integer(), nullable=True),
    sa.Column('aprovado_por', sa.Integer(), nullable=True),
    sa.Column('data_aprovacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acao_corretiva', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aprovado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativos.id'], ),
    sa.ForeignKeyConstraint(['auditoria_id'], ['auditorias.id'], ),
    sa.ForeignKeyConstraint(['coletado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['local_encontrado_id'], ['locais.id'], ),
    sa.ForeignKeyConstraint(['local_esperado_id'], ['locais.id'], ),
    sa.ForeignKeyConstraint(['responsavel_esperado_id'], ['responsaveis.id'], ),
    sa.ForeignKeyConstraint(['verificado_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_itens_id'), 'auditoria_itens', ['id'], unique=False)
    op.create_table('manutencoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_chamado', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('ativo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('prioridade', sa.String(length=10), nullable=False),
    sa.Column('categoria_problema', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('data_abertura', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('data_inicio_atendimento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_resolucao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_fechamento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_horas', sa.Integer(), nullable=True),
    sa.Column('data_vencimento_sla', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_pausado', sa.Integer(), nullable=True),
    sa.Column('tempo_pausado_minutos', sa.Integer(), nullable=True),
    sa.Column('aberto_por', sa.Integer(), nullable=False),
    sa.Column('atribuido_para', sa.Integer(), nullable=True),
    sa.Column('aprovado_por', sa.Integer(), nullable=True),
    sa.Column('custo_estimado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('custo_real', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('custo_pecas', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('custo_mao_obra', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tempo_downtime_minutos', sa.Integer(), nullable=True),
    sa.Column('impacto_operacional', sa.String(length=20), nullable=True),
    sa.Column('solucao', sa.Text(), nullable=True),
    sa.Column('causa_raiz', sa.Text(), nullable=True),
    sa.Column('pecas_utilizadas', sa.Text(), nullable=True),
    sa.Column('fornecedor_servico', sa.String(length=150), nullable=True),
    sa.Column('numero_os_externa', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('satisfacao_usuario', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aberto_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['aprovado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativos.id'], ),
    sa.ForeignKeyConstraint(['atribuido_para'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manutencoes_id'), 'manutencoes', ['id'], unique=False)
    op.create_index(op.f('ix_manutencoes_numero_chamado'), 'manutencoes', ['numero_chamado'], unique=True)
    op.create_table('movimentacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('motivo', sa.String(length=200), nullable=False),
    sa.Column('de_local_id', sa.Integer(), nullable=True),
    sa.Column('para_local_id', sa.Integer(), nullable=True),
    sa.Column('de_responsavel_id', sa.Integer(), nullable=True),
    sa.Column('para_responsavel_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_solicitacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('data_aprovacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('solicitado_por', sa.Integer(), nullable=False),
    sa.Column('aprovado_por', sa.Integer(), nullable=True),
    sa.Column('executado_por', sa.Integer(), nullable=True),
    sa.Column('termo_responsabilidade_url', sa.String(length=500), nullable=True),
    sa.Column('termo_assinado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('valor_limite_aprovacao', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aprovado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativos.id'], ),
    sa.ForeignKeyConstraint(['de_local_id'], ['locais.id'], ),
    sa.ForeignKeyConstraint(['de_responsavel_id'], ['responsaveis.id'], ),
    sa.ForeignKeyConstraint(['executado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['para_local_id'], ['locais.id'], ),
    sa.ForeignKeyConstraint(['para_responsavel_id'], ['responsaveis.id'], ),
    sa.ForeignKeyConstraint(['solicitado_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimentacoes_id'), 'movimentacoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimentacoes_id'), table_name='movimentacoes')
    op.drop_table('movimentacoes')
    op.drop_index(op.f('ix_manutencoes_numero_chamado'), table_name='manutencoes')
    op.drop_index(op.f('ix_manutencoes_id'), table_name='manutencoes')
    op.drop_table('manutencoes')
    op.drop_index(op.f('ix_auditoria_itens_id'), table_name='auditoria_itens')
    op.drop_table('auditoria_itens')
    op.drop_index(op.f('ix_ticket_comments_ticket_id'), table_name='ticket_comments')
    op.drop_index(op.f('ix_ticket_comments_id'), table_name='ticket_comments')
    op.drop_table('ticket_comments')
    op.drop_index(op.f('ix_ativos_patrimonio'), table_name='ativos')
    op.drop_index(op.f('ix_ativos_ns_serie'), table_name='ativos')
    op.drop_index(op.f('ix_ativos_id'), table_name='ativos')
    op.drop_index(op.f('ix_ativos_codigo'), table_name='ativos')
    op.drop_table('ativos')
    op.drop_index(op.f('ix_tickets_ticket_number'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_priority'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_machine_hostname'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_location_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_category'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assigned_to'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_asset_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_software_inventory_name'), table_name='software_inventory')
    op.drop_index(op.f('ix_software_inventory_machine_id'), table_name='software_inventory')
    op.drop_index(op.f('ix_software_inventory_id'), table_name='software_inventory')
    op.drop_table('software_inventory')
    op.drop_index(op.f('ix_responsaveis_nome'), table_name='responsaveis')
    op.drop_index(op.f('ix_responsaveis_matricula'), table_name='responsaveis')
    op.drop_index(op.f('ix_responsaveis_id'), table_name='responsaveis')
    op.drop_index(op.f('ix_responsaveis_email'), table_name='responsaveis')
    op.drop_table('responsaveis')
    op.drop_index(op.f('ix_movements_to_user_id'), table_name='movements')
    op.drop_index(op.f('ix_movements_to_location_id'), table_name='movements')
    op.drop_index(op.f('ix_movements_status'), table_name='movements')
    op.drop_index(op.f('ix_movements_movement_type'), table_name='movements')
    op.drop_index(op.f('ix_movements_movement_number'), table_name='movements')
    op.drop_index(op.f('ix_movements_id'), table_name='movements')
    op.drop_index(op.f('ix_movements_from_user_id'), table_name='movements')
    op.drop_index(op.f('ix_movements_from_location_id'), table_name='movements')
    op.drop_index(op.f('ix_movements_asset_id'), table_name='movements')
    op.drop_table('movements')
    op.drop_index(op.f('ix_machine_metrics_recorded_at'), table_name='machine_metrics')
    op.drop_index(op.f('ix_machine_metrics_metric_name'), table_name='machine_metrics')
    op.drop_index(op.f('ix_machine_metrics_machine_id'), table_name='machine_metrics')
    op.drop_index(op.f('ix_machine_metrics_id'), table_name='machine_metrics')
    op.drop_index(op.f('ix_machine_metrics_category'), table_name='machine_metrics')
    op.drop_table('machine_metrics')
    op.drop_index(op.f('ix_locais_id'), table_name='locais')
    op.drop_index(op.f('ix_locais_codigo'), table_name='locais')
    op.drop_table('locais')
    op.drop_index(op.f('ix_asset_audits_id'), table_name='asset_audits')
    op.drop_index(op.f('ix_asset_audits_asset_id'), table_name='asset_audits')
    op.drop_index(op.f('ix_asset_audits_action'), table_name='asset_audits')
    op.drop_table('asset_audits')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_source'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_machine_hostname'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_location_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_correlation_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_category'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_asset_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_number'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_setores_nome'), table_name='setores')
    op.drop_index(op.f('ix_setores_id'), table_name='setores')
    op.drop_index(op.f('ix_setores_codigo'), table_name='setores')
    op.drop_table('setores')
    op.drop_index(op.f('ix_machines_status'), table_name='machines')
    op.drop_index(op.f('ix_machines_operating_system'), table_name='machines')
    op.drop_index(op.f('ix_machines_machine_type'), table_name='machines')
    op.drop_index(op.f('ix_machines_machine_id'), table_name='machines')
    op.drop_index(op.f('ix_machines_mac_address'), table_name='machines')
    op.drop_index(op.f('ix_machines_location_id'), table_name='machines')
    op.drop_index(op.f('ix_machines_ip_address'), table_name='machines')
    op.drop_index(op.f('ix_machines_id'), table_name='machines')
    op.drop_index(op.f('ix_machines_hostname'), table_name='machines')
    op.drop_index(op.f('ix_machines_assigned_user_id'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_auditorias_id'), table_name='auditorias')
    op.drop_index(op.f('ix_auditorias_codigo'), table_name='auditorias')
    op.drop_table('auditorias')
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_location_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_tag'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_alert_rules_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_code'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_fornecedores_nome'), table_name='fornecedores')
    op.drop_index(op.f('ix_fornecedores_id'), table_name='fornecedores')
    op.drop_index(op.f('ix_fornecedores_cpf'), table_name='fornecedores')
    op.drop_index(op.f('ix_fornecedores_cnpj'), table_name='fornecedores')
    op.drop_table('fornecedores')
    op.drop_index(op.f('ix_centros_custo_nome'), table_name='centros_custo')
    op.drop_index(op.f('ix_centros_custo_id'), table_name='centros_custo')
    op.drop_index(op.f('ix_centros_custo_codigo'), table_name='centros_custo')
    op.drop_table('centros_custo')
    # ### end Alembic commands ###